services:
  postgresql:
    image: postgres:16-alpine
    volumes:
      - $PWD/db:/var/lib/postgresql/data
      - $PWD/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=test#setup
      - POSTGRES_USER=atlassian
      - POSTGRES_MULTIPLE_DATABASES=jira,confluence,bitbucket
    profiles:
      - jira
      - confluence
      - bitbucket

  jira:
    image: atlassian/jira-software:10.3.2
    ports:
      - 8080:8080
    volumes:
      - $PWD/jira:/var/atlassian/application-data/jira
    environment:
      - JVM_SUPPORT_RECOMMENDED_ARGS="-Dupm.plugin.upload.enabled=true"
    profiles:
      - jira

  confluence:
    image: atlassian/confluence:9.0.2
    ports:
      - 8080:8090
    volumes:
      - $PWD/confluence:/var/atlassian/application-data/confluence
    environment:
      - JVM_SUPPORT_RECOMMENDED_ARGS="-Dupm.plugin.upload.enabled=true"
    profiles:
      - confluence

  bitbucket:
    image: atlassian/bitbucket:9.4.3
    ports:
      - 8080:7990
    volumes:
      - $PWD/bitbucket:/var/atlassian/application-data/bitbucket
    environment:
      - JVM_SUPPORT_RECOMMENDED_ARGS="-Dupm.plugin.upload.enabled=true"
      # Disable embedded open search to make it more lightweight
      - SEARCH_ENABLED=false
      # Adjust the below settings to match your testing environment if coming from a public URL
      # if not, bitbucket will give XSRF errors.
      #- SERVER_PROXY_NAME=yourpublicdomain.com
      #- SERVER_PROXY_PORT=443
      #- SERVER_SCHEME=https
      #- SERVER_SECURE=true
    profiles:
      - bitbucket
