name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Set up Atlassian SDK
        run: ./.github/workflows/scripts/setup_atlas.sh
      - name: Run tests
        run: atlas-mvn --batch-mode clean test
      - name: Set version to PR reference
        run: atlas-mvn --batch-mode versions:set -DnewVersion=PR-${{ github.event.pull_request.number }}
      - name: Package preview Jars
        run: atlas-mvn --batch-mode package -Dmaven.test.skip=true
      - name: "Push artifact: Bitbucket Plugin PR-${{ github.event.pull_request.number }}"
        uses: actions/upload-artifact@v4
        with:
          name: Bitbucket Plugin PR-${{ github.event.pull_request.number }}
          path: "./bitbucket-plugin/target/*.jar"
          compression-level: 0
          overwrite: true
          retention-days: 7
      - name: "Push artifact: Confluence Plugin PR-${{ github.event.pull_request.number }}"
        uses: actions/upload-artifact@v4
        with:
          name: Confluence Plugin PR-${{ github.event.pull_request.number }}
          path: "./confluence-plugin/target/*.jar"
          compression-level: 0
          overwrite: true
          retention-days: 7
      - name: "Push artifact: JIRA Plugin PR-${{ github.event.pull_request.number }}"
        uses: actions/upload-artifact@v4
        with:
          name: JIRA Plugin PR-${{ github.event.pull_request.number }}
          path: "./jira-plugin/target/*.jar"
          compression-level: 0
          overwrite: true
          retention-days: 7