# Using semantic release it will package the plugin jars
# using the next semantic version inferred from commits between
# the latest tag and the HEAD of the branch.
#
# The generate JAR files are going to be published in Github
# Releases page together with the changelog.
#

name: Release

on:
  push:
    branches:
      - 'master'

jobs:
  semantic-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Set up Atlassian SDK
        run: ./.github/workflows/scripts/setup_atlas.sh
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
